name: Bezelbub
options:
  bundleIdPrefix: co.dgrlabs
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  DEVELOPMENT_TEAM: 4W2V3Q3VA4
  CODE_SIGN_STYLE: Automatic

schemes:
  Bezelbub:
    build:
      targets:
        Bezelbub: all

targets:
  Bezelbub:
    type: application
    platform: macOS
    sources:
      - path: Bezelbub
      - path: Resources/Bezels
        buildPhase: resources
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: co.dgrlabs.bezelbub
      INFOPLIST_FILE: Bezelbub/Info.plist
      PRODUCT_NAME: Bezelbub
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      COMBINE_HIDPI_IMAGES: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      CODE_SIGN_ENTITLEMENTS: Bezelbub/Bezelbub.entitlements
      ENABLE_HARDENED_RUNTIME: YES
      INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 DGR Labs, LLC. All rights reserved."
