name: OnDevice
options:
  bundleIdPrefix: co.dgrlabs
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  DEVELOPMENT_TEAM: 4W2V3Q3VA4
  CODE_SIGN_STYLE: Automatic

targets:
  OnDevice:
    type: application
    platform: macOS
    sources:
      - path: OnDevice
      - path: Resources/Bezels
        buildPhase: resources
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: co.dgrlabs.framer
      INFOPLIST_FILE: OnDevice/Info.plist
      PRODUCT_NAME: OnDevice
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      COMBINE_HIDPI_IMAGES: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      CODE_SIGN_ENTITLEMENTS: OnDevice/OnDevice.entitlements
